// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file_streaming.proto
#ifndef GRPC_file_5fstreaming_2eproto__INCLUDED
#define GRPC_file_5fstreaming_2eproto__INCLUDED

#include "file_streaming.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace routeguide {

class FileStreaming final {
 public:
  static constexpr char const* service_full_name() {
    return "routeguide.FileStreaming";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::routeguide::FileToStream>> downloadFile(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::routeguide::FileToStream>>(downloadFileRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::routeguide::FileToStream>> AsyncdownloadFile(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::routeguide::FileToStream>>(AsyncdownloadFileRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::routeguide::FileToStream>> PrepareAsyncdownloadFile(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::routeguide::FileToStream>>(PrepareAsyncdownloadFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriterInterface< ::routeguide::FileToStream>> uploadFile(::grpc::ClientContext* context, ::routeguide::StreamingError* response) {
      return std::unique_ptr< ::grpc::ClientWriterInterface< ::routeguide::FileToStream>>(uploadFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::routeguide::FileToStream>> AsyncuploadFile(::grpc::ClientContext* context, ::routeguide::StreamingError* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::routeguide::FileToStream>>(AsyncuploadFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::routeguide::FileToStream>> PrepareAsyncuploadFile(::grpc::ClientContext* context, ::routeguide::StreamingError* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriterInterface< ::routeguide::FileToStream>>(PrepareAsyncuploadFileRaw(context, response, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void downloadFile(::grpc::ClientContext* context, ::routeguide::TargetFileName* request, ::grpc::experimental::ClientReadReactor< ::routeguide::FileToStream>* reactor) = 0;
      virtual void uploadFile(::grpc::ClientContext* context, ::routeguide::StreamingError* response, ::grpc::experimental::ClientWriteReactor< ::routeguide::FileToStream>* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientReaderInterface< ::routeguide::FileToStream>* downloadFileRaw(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::routeguide::FileToStream>* AsyncdownloadFileRaw(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::routeguide::FileToStream>* PrepareAsyncdownloadFileRaw(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientWriterInterface< ::routeguide::FileToStream>* uploadFileRaw(::grpc::ClientContext* context, ::routeguide::StreamingError* response) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::routeguide::FileToStream>* AsyncuploadFileRaw(::grpc::ClientContext* context, ::routeguide::StreamingError* response, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncWriterInterface< ::routeguide::FileToStream>* PrepareAsyncuploadFileRaw(::grpc::ClientContext* context, ::routeguide::StreamingError* response, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    std::unique_ptr< ::grpc::ClientReader< ::routeguide::FileToStream>> downloadFile(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::routeguide::FileToStream>>(downloadFileRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::routeguide::FileToStream>> AsyncdownloadFile(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::routeguide::FileToStream>>(AsyncdownloadFileRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::routeguide::FileToStream>> PrepareAsyncdownloadFile(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::routeguide::FileToStream>>(PrepareAsyncdownloadFileRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientWriter< ::routeguide::FileToStream>> uploadFile(::grpc::ClientContext* context, ::routeguide::StreamingError* response) {
      return std::unique_ptr< ::grpc::ClientWriter< ::routeguide::FileToStream>>(uploadFileRaw(context, response));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::routeguide::FileToStream>> AsyncuploadFile(::grpc::ClientContext* context, ::routeguide::StreamingError* response, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::routeguide::FileToStream>>(AsyncuploadFileRaw(context, response, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncWriter< ::routeguide::FileToStream>> PrepareAsyncuploadFile(::grpc::ClientContext* context, ::routeguide::StreamingError* response, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncWriter< ::routeguide::FileToStream>>(PrepareAsyncuploadFileRaw(context, response, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void downloadFile(::grpc::ClientContext* context, ::routeguide::TargetFileName* request, ::grpc::experimental::ClientReadReactor< ::routeguide::FileToStream>* reactor) override;
      void uploadFile(::grpc::ClientContext* context, ::routeguide::StreamingError* response, ::grpc::experimental::ClientWriteReactor< ::routeguide::FileToStream>* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientReader< ::routeguide::FileToStream>* downloadFileRaw(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request) override;
    ::grpc::ClientAsyncReader< ::routeguide::FileToStream>* AsyncdownloadFileRaw(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::routeguide::FileToStream>* PrepareAsyncdownloadFileRaw(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientWriter< ::routeguide::FileToStream>* uploadFileRaw(::grpc::ClientContext* context, ::routeguide::StreamingError* response) override;
    ::grpc::ClientAsyncWriter< ::routeguide::FileToStream>* AsyncuploadFileRaw(::grpc::ClientContext* context, ::routeguide::StreamingError* response, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncWriter< ::routeguide::FileToStream>* PrepareAsyncuploadFileRaw(::grpc::ClientContext* context, ::routeguide::StreamingError* response, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_downloadFile_;
    const ::grpc::internal::RpcMethod rpcmethod_uploadFile_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status downloadFile(::grpc::ServerContext* context, const ::routeguide::TargetFileName* request, ::grpc::ServerWriter< ::routeguide::FileToStream>* writer);
    virtual ::grpc::Status uploadFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::routeguide::FileToStream>* reader, ::routeguide::StreamingError* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_downloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_downloadFile() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_downloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status downloadFile(::grpc::ServerContext* /*context*/, const ::routeguide::TargetFileName* /*request*/, ::grpc::ServerWriter< ::routeguide::FileToStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdownloadFile(::grpc::ServerContext* context, ::routeguide::TargetFileName* request, ::grpc::ServerAsyncWriter< ::routeguide::FileToStream>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_uploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_uploadFile() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_uploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status uploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::routeguide::FileToStream>* /*reader*/, ::routeguide::StreamingError* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestuploadFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::routeguide::StreamingError, ::routeguide::FileToStream>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_downloadFile<WithAsyncMethod_uploadFile<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_downloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_downloadFile() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackServerStreamingHandler< ::routeguide::TargetFileName, ::routeguide::FileToStream>(
          [this] { return this->downloadFile(); }));
    }
    ~ExperimentalWithCallbackMethod_downloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status downloadFile(::grpc::ServerContext* /*context*/, const ::routeguide::TargetFileName* /*request*/, ::grpc::ServerWriter< ::routeguide::FileToStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerWriteReactor< ::routeguide::TargetFileName, ::routeguide::FileToStream>* downloadFile() {
      return new ::grpc_impl::internal::UnimplementedWriteReactor<
        ::routeguide::TargetFileName, ::routeguide::FileToStream>;}
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_uploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_uploadFile() {
      ::grpc::Service::experimental().MarkMethodCallback(1,
        new ::grpc_impl::internal::CallbackClientStreamingHandler< ::routeguide::FileToStream, ::routeguide::StreamingError>(
          [this] { return this->uploadFile(); }));
    }
    ~ExperimentalWithCallbackMethod_uploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status uploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::routeguide::FileToStream>* /*reader*/, ::routeguide::StreamingError* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerReadReactor< ::routeguide::FileToStream, ::routeguide::StreamingError>* uploadFile() {
      return new ::grpc_impl::internal::UnimplementedReadReactor<
        ::routeguide::FileToStream, ::routeguide::StreamingError>;}
  };
  typedef ExperimentalWithCallbackMethod_downloadFile<ExperimentalWithCallbackMethod_uploadFile<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_downloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_downloadFile() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_downloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status downloadFile(::grpc::ServerContext* /*context*/, const ::routeguide::TargetFileName* /*request*/, ::grpc::ServerWriter< ::routeguide::FileToStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_uploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_uploadFile() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_uploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status uploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::routeguide::FileToStream>* /*reader*/, ::routeguide::StreamingError* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_downloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_downloadFile() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_downloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status downloadFile(::grpc::ServerContext* /*context*/, const ::routeguide::TargetFileName* /*request*/, ::grpc::ServerWriter< ::routeguide::FileToStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestdownloadFile(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_uploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_uploadFile() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_uploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status uploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::routeguide::FileToStream>* /*reader*/, ::routeguide::StreamingError* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestuploadFile(::grpc::ServerContext* context, ::grpc::ServerAsyncReader< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* reader, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncClientStreaming(1, context, reader, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_downloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_downloadFile() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this] { return this->downloadFile(); }));
    }
    ~ExperimentalWithRawCallbackMethod_downloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status downloadFile(::grpc::ServerContext* /*context*/, const ::routeguide::TargetFileName* /*request*/, ::grpc::ServerWriter< ::routeguide::FileToStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerWriteReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* downloadFile() {
      return new ::grpc_impl::internal::UnimplementedWriteReactor<
        ::grpc::ByteBuffer, ::grpc::ByteBuffer>;}
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_uploadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_uploadFile() {
      ::grpc::Service::experimental().MarkMethodRawCallback(1,
        new ::grpc_impl::internal::CallbackClientStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this] { return this->uploadFile(); }));
    }
    ~ExperimentalWithRawCallbackMethod_uploadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status uploadFile(::grpc::ServerContext* /*context*/, ::grpc::ServerReader< ::routeguide::FileToStream>* /*reader*/, ::routeguide::StreamingError* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::experimental::ServerReadReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* uploadFile() {
      return new ::grpc_impl::internal::UnimplementedReadReactor<
        ::grpc::ByteBuffer, ::grpc::ByteBuffer>;}
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_downloadFile : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_downloadFile() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler< ::routeguide::TargetFileName, ::routeguide::FileToStream>(std::bind(&WithSplitStreamingMethod_downloadFile<BaseClass>::StreameddownloadFile, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithSplitStreamingMethod_downloadFile() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status downloadFile(::grpc::ServerContext* /*context*/, const ::routeguide::TargetFileName* /*request*/, ::grpc::ServerWriter< ::routeguide::FileToStream>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreameddownloadFile(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::routeguide::TargetFileName,::routeguide::FileToStream>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_downloadFile<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_downloadFile<Service > StreamedService;
};

}  // namespace routeguide


#endif  // GRPC_file_5fstreaming_2eproto__INCLUDED
