// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: file_streaming.proto

#include "file_streaming.pb.h"
#include "file_streaming.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace routeguide {

static const char* FileStreaming_method_names[] = {
  "/routeguide.FileStreaming/downloadFile",
  "/routeguide.FileStreaming/uploadFile",
};

std::unique_ptr< FileStreaming::Stub> FileStreaming::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FileStreaming::Stub> stub(new FileStreaming::Stub(channel));
  return stub;
}

FileStreaming::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_downloadFile_(FileStreaming_method_names[0], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_uploadFile_(FileStreaming_method_names[1], ::grpc::internal::RpcMethod::CLIENT_STREAMING, channel)
  {}

::grpc::ClientReader< ::routeguide::FileToStream>* FileStreaming::Stub::downloadFileRaw(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request) {
  return ::grpc_impl::internal::ClientReaderFactory< ::routeguide::FileToStream>::Create(channel_.get(), rpcmethod_downloadFile_, context, request);
}

void FileStreaming::Stub::experimental_async::downloadFile(::grpc::ClientContext* context, ::routeguide::TargetFileName* request, ::grpc::experimental::ClientReadReactor< ::routeguide::FileToStream>* reactor) {
  ::grpc_impl::internal::ClientCallbackReaderFactory< ::routeguide::FileToStream>::Create(stub_->channel_.get(), stub_->rpcmethod_downloadFile_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::routeguide::FileToStream>* FileStreaming::Stub::AsyncdownloadFileRaw(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::routeguide::FileToStream>::Create(channel_.get(), cq, rpcmethod_downloadFile_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::routeguide::FileToStream>* FileStreaming::Stub::PrepareAsyncdownloadFileRaw(::grpc::ClientContext* context, const ::routeguide::TargetFileName& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncReaderFactory< ::routeguide::FileToStream>::Create(channel_.get(), cq, rpcmethod_downloadFile_, context, request, false, nullptr);
}

::grpc::ClientWriter< ::routeguide::FileToStream>* FileStreaming::Stub::uploadFileRaw(::grpc::ClientContext* context, ::routeguide::StreamingError* response) {
  return ::grpc_impl::internal::ClientWriterFactory< ::routeguide::FileToStream>::Create(channel_.get(), rpcmethod_uploadFile_, context, response);
}

void FileStreaming::Stub::experimental_async::uploadFile(::grpc::ClientContext* context, ::routeguide::StreamingError* response, ::grpc::experimental::ClientWriteReactor< ::routeguide::FileToStream>* reactor) {
  ::grpc_impl::internal::ClientCallbackWriterFactory< ::routeguide::FileToStream>::Create(stub_->channel_.get(), stub_->rpcmethod_uploadFile_, context, response, reactor);
}

::grpc::ClientAsyncWriter< ::routeguide::FileToStream>* FileStreaming::Stub::AsyncuploadFileRaw(::grpc::ClientContext* context, ::routeguide::StreamingError* response, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc_impl::internal::ClientAsyncWriterFactory< ::routeguide::FileToStream>::Create(channel_.get(), cq, rpcmethod_uploadFile_, context, response, true, tag);
}

::grpc::ClientAsyncWriter< ::routeguide::FileToStream>* FileStreaming::Stub::PrepareAsyncuploadFileRaw(::grpc::ClientContext* context, ::routeguide::StreamingError* response, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncWriterFactory< ::routeguide::FileToStream>::Create(channel_.get(), cq, rpcmethod_uploadFile_, context, response, false, nullptr);
}

FileStreaming::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileStreaming_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< FileStreaming::Service, ::routeguide::TargetFileName, ::routeguide::FileToStream>(
          std::mem_fn(&FileStreaming::Service::downloadFile), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileStreaming_method_names[1],
      ::grpc::internal::RpcMethod::CLIENT_STREAMING,
      new ::grpc::internal::ClientStreamingHandler< FileStreaming::Service, ::routeguide::FileToStream, ::routeguide::StreamingError>(
          std::mem_fn(&FileStreaming::Service::uploadFile), this)));
}

FileStreaming::Service::~Service() {
}

::grpc::Status FileStreaming::Service::downloadFile(::grpc::ServerContext* context, const ::routeguide::TargetFileName* request, ::grpc::ServerWriter< ::routeguide::FileToStream>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status FileStreaming::Service::uploadFile(::grpc::ServerContext* context, ::grpc::ServerReader< ::routeguide::FileToStream>* reader, ::routeguide::StreamingError* response) {
  (void) context;
  (void) reader;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace routeguide

